name: Build Project
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Archive Project Files
        run: |
          mkdir build
          cp index.html build/
          cp -r backend build/
          cp -r database build/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: school-project-files
          path: build/
